apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cmc

resources:
  - web.yaml

# Rewritten by CI alongside the API and worker tags, so the whole system runs
# one build.
images:
  - name: ghcr.io/akashungarala/car-maintenance-companion/web
    newTag: d6fb6846b84328c0eebc1ccfe74ff40b827d4b69
