apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cmc

resources:
  - web.yaml

# Rewritten by CI alongside the API and worker tags, so the whole system runs
# one build.
images:
  - name: ghcr.io/akashungarala/car-maintenance-companion/web
    newTag: 02ecf1fc7d6310ed5eb88b7d51fe5272861302d1
