---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-backup-s3
  namespace: cmc
spec:
  encryptedData:
    ACCESS_KEY_ID: AgA5pXjwp+tNB4fl02Fr9dK7+Sttd8kxv+J/VPctT8Y3Dgc0Zv+HVWF4aQn+st50SdHwklHKMlFv5B4d+BXpbPML2kGteNOsmCvzPSd8e/ajmToV0+H9x8W/Ujv4VAQP4zniV+vsuH5bIq4YEj9a/0biip+pgK2J1S142yaVKjDGt9EUyVGMeRZ6EIdUqRvJMMxASakFmK92Xxk1/UkndI1I9KiYeWuk+Etf4++0tOv6Pm8CU6Ev+HVuiWpa/whprJBzqWiyROUXVvdJPx0aomqg554qtv7N5JZnNWhZURNWj5WbYQ7/+WlhRdts3VtZeTVYSfgovxltgpATnTBTpMLJzkbjAyhW5PyRMOUfwKlaTtbujdA5GFsOqHidKm8tU5ce9/bgTvIEAGIg5GffWF1PYlYjzbNlWXIp87WYlvsDDdLTcJLYk5mh3Dq2M2G7HOMU2eT+7z0eL5Sms2e0K6T4RMK7jVoelK0Zm8/K1FfAgnR7S5lIHgtW/0CcrtncpuQ27zU9YoFJkOLykybUJo2vBJfJ6T67HjH9Am5QYnp+O7gfV+zHo7GzBnOV8o/iMsF6j0/ZYbsl1B0OVXaqtp7t5nXgeFTT7GCCQ2X1qIuioM0NL4ELx9ZukAS9hK+0lkRihDuCcvUNLDnCYEtl9uabxHJD8GsrprXfAT2ckU7aabMA+p0J1R35Mc29CSr377rxeQk9BAfefZCanidJsZ3xUp9MmKQVW2GPzWVVltfC9KFCKfFHW5Tz
    ACCESS_SECRET_KEY: AgAFr1TPnUbwCgu1Lqjk1BhxCC5A5RDHprrdaIspu7mvKrxO7NG8f6k19ldAVd6n7oMBQ+Hd4da/ed1ZtoiNMGbvYQYFi07IX+O8OFBFlLeorhsvyy1CO8FhSmfDTYyS0bPEc+wwfg38J1Uvo6hU2DnsNPdMR6NP4MVwROpNDHsIC39djMG84bNCTII0PBL9jCC0gkUR4K3xxm0eCuDwSaNlZgeDxjawFPq826vXMRxm9nLebiLVVx81gKKATjDfAEWwuVpJZoCuBlAbbFTyna4WU1Ilsij2coNXjYf8EPrV2bFmK37p4NL2sfnwmqp4cuezV9914jjLNpAG65kc7qtgYJtC6NT0ZXj7NwtZNEdKzBMv1DYeWEyj9a4aNlgtj2JvvEzGKAL5XE3pB/UMv1MytsBjxW0hPqhJ1qwtad+PKhO2FV6dwnMP4bXHaux5LdQECYcTwfnsyxG4vexLaOptKMMZjwVbmFck/7jYfLEKIKp8HLxOjOQJdicBeTQAEZxobkJ5qv+ngtukSCfMF46BYQSfc9n2sElUqrYxdPNbT+KtD7mT98Iu3D78G0a8A8wp2IO1ze7CBxxd2OfIO+GGKS00HRiV0qMIpu1U2zfZ1LfAvWxaMzR4sIm3ztEGY9Rpp2NcY6J21YcypV65yffoMAgatHuinn6uZwgF8JJOIQggPSYWcZwOd3SWG9kqsU76Im+4kSeoPpQ5b29+9/6STV+2NBiX2v6uiTp2kO0RI4B2B98pX1w1VpmOnw==
  template:
    metadata:
      name: pg-backup-s3
      namespace: cmc
