---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-otlp
  namespace: cmc
spec:
  encryptedData:
    AUTHORIZATION: AgAmUlemT3LgsuzxjXWnNEkukO0xOOoA7AzEwgYzd35ZEucvo3SfkymPGgG7SM+pAveUkJzNNsqDZJi+RJQ8sB6rexlO3BPhGJZNjDwNE3x89bKpRstkkwMsd2ycL8ghcJsiLLgqtgSpKVJDzvpEHu5qJMdFpklB5iR6iZQ9aB+OvkYbRndJ4LTvjqKAtDTjBsoqMBSuLwlJ1QXK2MuxDAtUd1hdBARyBGRjFkMso5D6RBi15RWup5PC9F0zz4ttxZg2mtAescOin7I/4hl92wo013y3lDaLhVeGEYiEM489ewYN9Kh4CaNRZ1cw5NZy/SZUvTNpRU/c3uPkpQwnGcY5AvLIvY2Z/Sq7CyyCHYXb9HY0VkGyegzZddCGSOn9la99ZA71BqYYpELLv80WrUq6WLIRDuArqMqKmFT3iwAdeppWZo7ECcBaXLOz010w4QC2efkprauFLTCS8YNqma4UXdKAS77J9r68UWl1z1q0GFGJyccO2S/XBJT+KVoIJyWT/nOJWu3/3iQ4Xtg6V4i+Rp9ON+WInzwWrRj16R5NiqLsEjGoxmkoTXWegeqhnlWgIhCoEU1+Y1oM9V6WIElgwhWynmLCgpHNRY++k0UOy7KnKFT8xcp7srOSSeB7w0lCVmDvsMmqUcQ/GoM7Vr2zyEf/mdxU3+vHZmVOnRfjxrN8usqjfxpdKIhCVTUWecssUAVM0nPbT7U7uutE63DG7YvWOZRGcDk0MjNj4VmpTAebMI3pHujbGQg5Z2dWauk0Zt3POPScflN2/sBuz2Ni0nCyZp62yYVpAMCah46AfkDwhEbPyiKDa862UkV3hK3nj2wrxxtVrfu+TOECOyvj0UN5r6grEXl+Ui0olQeg/1cJkOimEEY8TLwyP3F19PGx/D5nii4n+i99gmoov8svK8uNQV6jjlo0A36Icd8apYAo51+WTtLzW28b4JIvyfGlNwKG6aRYgfihZ5TW0ky5KNB5kEzbqHVncrJfrx7KJDZ0gFWIJqvLrzO19rMlJsNUHC5vj6kmE772/46geA==
  template:
    metadata:
      name: grafana-otlp
      namespace: cmc
