apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  source:
    repoURL: https://github.com/akashungarala/car-maintenance-companion.git
    targetRevision: deploy
    path: infra/k8s/apps/worker
  destination:
    server: https://kubernetes.default.svc
    namespace: cmc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
